### ISSUE TITLE
[Feature] Fee for "target" / selecting a bounty

### ISSUE THREAD

**Issue by TomLewis** [Indyuce/bounty-hunters#100]
When a player accepts a target for a bounty, allow us to set a fee, wouldn't be much, might be nice to be a set fee or a percentage of the current bounty price (another tax). this then stacks up if multiple peolpe accept a bounty and acts as a nice sink hole for an eco, even if its small! It also stops abuse! even if its set at $1 people think twice about it!

**Comment by Indyuce** [comment]
Being implemented

**Comment by TomLewis** [comment]
Woohoo!
