### ISSUE TITLE
Titles and animations not working

### ISSUE THREAD

**Issue by ValhallaCraft** [Indyuce/bounty-hunters#107]
My titles and animations are not showing in game. Permissions are all set to true but nothing comes up.

**Comment by Indyuce** [comment]
Are you able to change your title and animation using commands? Have you checked your console for error logs?

**Comment by ValhallaCraft** [comment]
So when I do /bounties title, it will show the title above the hotbar and that's it. Can't do anything else with it. It will not show up on the leaderboard.

**Comment by ValhallaCraft** [comment]
I will check console in a bit.

**Comment by ValhallaCraft** [comment]
Alright so console just says i ran the command and nothing past that

**Comment by Indyuce** [comment]
Check your console for plugin startup errors

**Comment by ValhallaCraft** [comment]
No Startup errors. Booted as intended

**Comment by iSeitan** [comment]
latest title shoudl apply automaticaly

**Comment by iSeitan** [comment]
my title and the placeholder doesnt work for me either

**Comment by iSeitan** [comment]
![2022-05-17_12 14 50](https://user-images.githubusercontent.com/86061857/168859272-4b4d5d0d-d84d-4cc7-91f8-21e50ffaffa4.png)

Placeholder dont show in VentureChat, nor Tab, nor scoreboard, nor in the /bounties title

**Comment by Indyuce** [comment]
This will be fixed in the next spigot release, basically it displays on action bar instead of chat
