### ISSUE TITLE
Dev builds for 1.18.2?

### ISSUE THREAD

**Issue by Kush-S-Patel** [Indyuce/bounty-hunters#112]
Hey there! Is there any chance that a dev build for BountyHunters Premium could be available somewhere? I bought the plugin but all of my BH dependent plugins fail to load on 1.18.2, because BH itself doesn't load. If a jar that works for 1.18.2 could be available I'd really appreciate it! Even i it's experimental I would be greatly appreciative, as a lot of my plugins depend on BH.

Thanks!

**Comment by S0ly** [comment]
yes me too plz 1.18.2

**Comment by adamwbb** [comment]
Agreed at least a dev build Its sad that bounty based servers that have upgraded to 1.18.2 cant function right now.

**Comment by Indyuce** [comment]
BH has no dev builds tho you can compile the source code on your end
