### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by nosewad** [Indyuce/bounty-hunters#129]
`Failed to execute goal on project BountyHunters: Could not resolve dependencies for project net.Indyuce:BountyHunters:jar:2.5-SNAPSHOT: de.simonsator:PartyAndFriends:jar:1.0.68 was not found in https://nexus.phoenixdvpt.fr/repository/maven-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of phoenix has elapsed or updates are forced -> [Help 1]`

**Comment by Indyuce** [comment]
Working on it
