### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by Triangulum598** [Indyuce/bounty-hunters#134]
Before I start, yes, I know that the plugin's own placeholders work.

However, when I use an external placeholder, such as this one that I made to properly format and abbreviate the bounties, it doesn't work for some reason.

![image](https://user-images.githubusercontent.com/78569904/208264688-1456a976-d6ad-4401-bd7c-7ca1a83283d5.png)

Having this sort of feature would allow for more customizability.

**Comment by Indyuce** [comment]
This will be implemented
