### ISSUE TITLE
[request] add few features

### ISSUE THREAD

**Issue by kassadGLA** [Indyuce/bounty-hunters#14]
Hello! Suggestions.
Add the `Failed hunts` stat, which keeps track of cases where the victim kills the hunter.
Add the stat `Killer factor` (%).
`Killer Factor = (Claimed bounties / Failed hunts) * 100`
(Include PAPI support for new stats).

In case the victim kills the hunter, then for this hunter automatically un-targeting this victim. A slain hunter can not longer set as target the victim who killed him (current bounty only).

Best regards.

**Comment by Indyuce** [comment]
Added to the trello!
