### ISSUE TITLE
Network check possibly uses the main thread

### ISSUE THREAD

**Issue by cuddylier** [Indyuce/bounty-hunters#15]
Hi

When my server has network issues, it seems that the server's main thread is potentially being frozen by bountyhunters trying to update or do some sort of other network interaction and failing due to the network issues on my end. Maybe an offline player check based on the stack trace output.

Example stack trace from paper: https://pastebin.com/raw/jBTMrdMR

All of the following stack traces after this one mentioned bountyhunters.

Thanks

**Comment by cuddylier** [comment]
I just typed "/bounties' there now after network issues stopped and it froze the server for 5 seconds so something odd is going on with that command and the fact it's doing it on the main thread. Typing it again after the first time typing it has no freezing affect so I assume it's caching something now.,

**Comment by Indyuce** [comment]
Seems like BH is trying to fetch player head textures from Minecraft servers on the main thread, I thought I moved these all to async but I'll have to dive into that

**Comment by Indyuce** [comment]
These head texture requests were indeed moved to async but the change is only available in the premium builds. I might push a more recent version to the legacy Spigot resource.
