### ISSUE TITLE
Bounties not being removed when claimed.

### ISSUE THREAD

**Issue by Repo31c** [Indyuce/bounty-hunters#17]
Plugin Version: 2.2.6
Server Version: 1.13.2
Server Software: PaperMC / Craftimize

Bounties for whatever reason are not removed when they are claimed.
No errors appear in console and this issue appeared suddenly a few weeks ago.
If it's any use, there were lots of bounties, well over 30, when the issue appeared.

This has resulted in players setting bounties on one another to farm for money.

**Comment by Indyuce** [comment]
I don't have that many players to test that on my end, I'll need more info about that issue

**Comment by Indyuce** [comment]
@Repo31c Any news on that issue?

**Comment by scannerGT** [comment]
Hi.

With BountyHunters Premium 2.3.7, on git-Paper-325 (api: 1.15.2-R0.1-SNAPSHOT) I have got this same problem.

The player received a bounty, no one who tries to kill him receives a prize. Of course, the bounty doesn't fall. I also tried with the bounty imposed by hand. I put on player A, player B killed player A - no effect. I attach my configuration file in gist.

https://gist.github.com/scannerGT/5accdabcb0e3cf78ee5e654ca51380d5

My plugins:

![Capto_Capture 2020-06-21_06-16-09_PM](https://user-images.githubusercontent.com/604892/85229712-c4489900-b3eb-11ea-9430-dc62d568219a.png)

**Comment by Indyuce** [comment]
Your config has several claim restrictions. Make sure the bounty owner is not the one claiming the bounty and that all players have the right permission to claim bounties.

Also it might not be the same issue, if I understood correctly OG's issue is that bounties are not removed but the money is being sent to the bounty claimers. If the bounty transaction is not processed either then that indicates BountyHunters simply ignores the bounty for another reason. Missing details on that issue to be able to work on it

**Comment by Indyuce** [comment]
Closed till further info is provided
