### ISSUE TITLE
Auto bounties increasement

### ISSUE THREAD

**Issue by baticag** [Indyuce/bounty-hunters#18]
Every time bounty, that is set automatically, kills another player, reward for him gets increased by number in config. I don't know if this is a bug, but if it isn't can you add an option for reward to be fixed on auto bounties? Thank you in advance!

**Comment by Indyuce** [comment]
It's the auto bounty feature, you can disable it in the config file. Auto bounties may also increase the current player's bounty if the target kills another player illegaly

**Comment by baticag** [comment]
I know that it is that feature but I want it to stop increasing money when it is already set and only offer fixed price for auto bounty. Can you make it possible?

**Comment by Indyuce** [comment]
Sure, I'll add an option for that.
