### ISSUE TITLE
Compass is not reset after bounty claim

### ISSUE THREAD

**Issue by kassadGLA** [Indyuce/bounty-hunters#2]
Compass is not reset after bounty claim. This is a critical bug that does not allow the use of the plugin on a production server. Because of this bug, you can torture a player until he has a nervous breakdown. All players who have a compass that aiming on victim will know its location even without an existing bounty (when bounty already claimed by someone). Compass will reset after server restart only.

**Comment by kassadGLA** [comment]
Add info. The same problem when bounty-creator just cancel bounty if before someone already set bounty as target and bought a compass.

**Comment by Indyuce** [comment]
I'll probably be replacing the tracking compass for a particle effect solution, it will be much cleaner and removes any possibility of stuck compass glitches.

**Comment by kassadGLA** [comment]
Hello!
I tested the last build you sent me. The problem persists, all the same, but with a new visual effect. Added another bug with sound. If you have activated the compass at least once, then right-clicking on any block is accompanied by a characteristic compass activation sound:
[Short video](https://youtu.be/LVOqXfxA0JQ)

I understand this badly and maybe what I write will be stupid. It may be necessary to make several checks every x seconds (it not really code):
```
if (targetPlayer is existingBounty && hunter set it as target) {
    if (targetPlayer is online) {
        if (targetPlayer in the same world) {
            compass can be used
        }  else {
               compass cannot be used because targetPlayer in the world worldName, reset compass
           }
    }  else {
           compass cannot be used because targetPlayer is offline, reset compass
       }
}  else {
       compass cannot be used because hunter is not have valid target, reset compass
   }
```

**Comment by Indyuce** [comment]
Fixed in the latest commit.
