### ISSUE TITLE
This error keeps me bugged

### ISSUE THREAD

**Issue by itsNSO** [Indyuce/bounty-hunters#21]
![image](https://user-images.githubusercontent.com/59635242/71949292-e0080c00-31ca-11ea-9126-ed35ddcb2bce.png)

when i connect plugin to my mysql databasa
it gives me this error. and in config file. first line is a comment. ;(

**Comment by Indyuce** [comment]
Can you send me the SQL BountyHunters config you used to reproduce the issue? (apart from the username and password obviously) MySQL support seems to work fine on my server, I'd like to know if it's some kind of database name syntax issue

**Comment by Webman97** [comment]
I'm experiencing this issue as well. My config (obviously with sensitive data replaced): https://pastebin.com/F3AaJs7p

**Comment by Indyuce** [comment]
Closed till further info is provided

**Comment by Webman97** [comment]
@Indyuce I provided all the info you asked for, what more do you want?
