### ISSUE TITLE
Editing the config makes it where bounties won't set

### ISSUE THREAD

**Issue by IvIurdoc** [Indyuce/bounty-hunters#23]
Using latest premium build on the Spigot page and then paper 1.15.2, when the config is edited from default values, /bounty won't work. The command runs but nothing happens, like if I do /bounty username 25, nothing pops up, no bounty is set.

**Comment by Indyuce** [comment]
Please pastebin your latest server logs

**Comment by Indyuce** [comment]
Closed till further info is provided
