### ISSUE TITLE
2.3.4/2.3.5 error on /bounties command on paper 1.15.2

### ISSUE THREAD

**Issue by minecraft7net** [Indyuce/bounty-hunters#24]
1.15.2
on spigot no errors
on paper errors like below 
tested on latest two version 2.3.5 and 2.3.4
https://pastebin.com/cKijxdj1

**Comment by Indyuce** [comment]
Just tried running BH on the latest paper build available online, seems to work fine. Logs provided say the plugin is disabled - double check your logs for plugin startup issues.

**Comment by Indyuce** [comment]
Closed till further info is provided
