### ISSUE TITLE
BountyHunter Premium [1.15.2] Error

### ISSUE THREAD

**Issue by BiGUNMAN** [Indyuce/bounty-hunters#27]
Paper: 129 [1.15.2]
Plugin Version: 2.3.6
Startup Errors: None
Error: https://media.discordapp.net/attachments/518513073888428061/690963511312121917/unknown.png

What we tried to do: Reset all BountyHunter Premium plugin files.

**Comment by Indyuce** [comment]
Please paste the entire server logs which include that error message

**Comment by SlimeCody** [comment]
![image](https://user-images.githubusercontent.com/49579480/79669606-4ca78500-8182-11ea-9f67-8da2d0b330d2.png)

We updated to 2.3.7

**Comment by Indyuce** [comment]
Please paste the **entire** corresponding **text** file

**Comment by Indyuce** [comment]
Closed till further info is provided
