### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by XipsAhoy** [Indyuce/bounty-hunters#29]
[13:32:50 ERROR]: [BountyHunters] Your server version is not handled with NMS.
How can I fix this error, when I start my server!?

**Comment by Indyuce** [comment]
You're using the wrong build for your server version. If you have access to BH Premium, use the latest version for 1.9-1.15 support.

If you are using BountyHunters Legacy, use 2.2.1 if you're running 1.8-1.12, use 2.2.6 if you're running 1.13+. It's clearly stated on the spigot plugin page, so read it again
