### ISSUE TITLE
Bounty-creator can set his own bounty as target

### ISSUE THREAD

**Issue by kassadGLA** [Indyuce/bounty-hunters#3]
Bounty-creator can set his own bounty as target. Yes, he cannot claim his bounty, but he can buy a compass, track the target until 2 conditions are met:
1. Until somebody claim this bounty.
2. Until the server is restarted (bug [issue #2](https://github.com/Indyuce/bounty-hunters/issues/2))

Also. If someone created a bounty on me, then I can open the bounty menu and set myself as a target. I can also buy a compass that will display a distance of 0 blocks.

**Comment by Indyuce** [comment]
Fix will be included in the next update
