### ISSUE TITLE
Saving Player Data Error

### ISSUE THREAD

**Issue by mtmustski** [Indyuce/bounty-hunters#41]
I have a console error every time a player disconnects.

[07:09:21 ERROR]: [BountyHunters] Could not save player data of mtmustski: No operations allowed after connection closed.
[07:09:21 ERROR]: [BountyHunters] Parsed player data: {Level=0, ClaimedBounties=0, SuccessfulBounties=0, IllegalKills=0, IllegalKillStreak=0, RedeemHeads=[]}

I am using a MySQL server which has a valid connection.  Below is my config file with MySQL user/pass removed.  Changed file ending from yml to txt for GitHub upload support but have the file named config.yml in the plugins folder.

[Config.txt](https://github.com/Indyuce/bounty-hunters/files/4690307/Config.txt)

**Comment by Indyuce** [comment]
Not a pro with MySQL unfortunately. Looks like for some reason the connection to the db just closes so the playerdata just can't be saved.. can I have a look at your server logs?

**Comment by mtmustski** [comment]
Sure thing, I attached a log from this morning.  The server version and plugin list is at the bottom of the log.  I'm currently running papermc build 82.  I can't swear to it, but I don't recall seeing the bug on papermc build 79.  

I can upload the sql db as well if you think that may be helpful.  I also realized I misspoke originally about using a MySQL server, it's actually running on a MariaDB server, although I don't think this should cause an issue. 

[latest.log](https://github.com/Indyuce/bounty-hunters/files/4897780/latest.log)

**Comment by Indyuce** [comment]
I'm affraid I can't help with that because I have no experience with MariaDB, have you tried using a MySQL server?

**Comment by mtmustski** [comment]
I ended up switching to using the default storage method without a SQL server.  I believe the root of my problem traces back to my database dropping inactive connections.  My server isn't big enough to where not having a db backend for storage would be an issue so I'll go ahead and close this issue.
