### ISSUE TITLE
Heads

### ISSUE THREAD

**Issue by PJKGitHub1** [Indyuce/bounty-hunters#45]
Hello, i purchased your plugin Bounty Hunters Legacy Premium, I want head drops disabled, so i set it to false just like the directions in the notes said. it didn't work, how do i fix this? The Config is below. Please get back to me soon. Sent you a message but you haven't responded
Thank You

head-hunting:
enabled: false

drop-head:

killer:
enabled: false
chance: 1

creator:
enabled: false
chance: 1

**Comment by Indyuce** [comment]
Using latest version it works fine on my end. It might be linked to #47, can you try and see if removing the tracking compass works on your end?
