### ISSUE TITLE
Unable to remove player tracking compass

### ISSUE THREAD

**Issue by TechnoVisionDev** [Indyuce/bounty-hunters#47]
I have set the player tracking feature to false, but nothing I do removed the player tracking compass from the bounties menu. Yes, I have tried restarting my server several tries and even deleting the plugin folder. The value is set to false but the tracker remains.

My Config: https://pastebin.com/VdvJEtMu

**Comment by Indyuce** [comment]
Not sure what's happening here. It looks like there is a larger issue where the plugin config does not save the changes made. Make sure your spigot build is up to date. Also I'd like to know if you're running Spigot or paper or another custom build, that could be the issue. I'm running latest 1.16 build from BuildTools and the config option seems to work fine
