### ISSUE TITLE
Bounties-menu visual bug.

### ISSUE THREAD

**Issue by kassadGLA** [Indyuce/bounty-hunters#5]
Latest build you sent me.
`Bounties` menu visual bug.
The test was attended by three players p1, p2, p3.
p1 creates bounty:
`/addbounty p2 100`
Now each player opens the bounty menu. When you hover over the bounty, each of the three players should see a different lore-description.
```
p1:
You set this bounty
The reward is $100
There are x players tracking him.

Right click to remove this bounty.
```
---
```
p2:
Set by p1.
The reward is $100
There are x players tracking him.

Don't let them kill you.
```
---
```
p3
Set by p1.
The reward is $100
There are x players tracking him.

Kill him to claim the bounty!
Click to (un)target him.
```
---
But all players see the same thing. For example, only the description intended for p1. After the server is restarted, this may randomly change and all players will see the description for p3.
In the screenshot below, a reward is created for the head of the player Kwai. Player Kwai opened the bounty menu, but he sees the lore-description as if he is a bounty-creator:
![bh](https://user-images.githubusercontent.com/42912751/60343188-1cf17b80-99bc-11e9-9aef-e524e181d938.png)

**Comment by Indyuce** [comment]
Fixed in the latest commit.
