### ISSUE TITLE
Bounties not loading up as server start up!

### ISSUE THREAD

**Issue by ExceptedPrism3** [Indyuce/bounty-hunters#54]
When booting up the server the BountyHunter doesn't load up and says that it didn't detect the [ vault ], but it's there and working fine with other plugins.
The start up error code:
[01:18:01 INFO]: [BountyHunters] Enabling BountyHunters v2.3.9
[01:18:02 INFO]: [BountyHunters] Detected Server Version: v1_15_R1
[01:18:02 ERROR]: [BountyHunters] Couldn't load Vault. Disabling...
[01:18:02 INFO]: [BountyHunters] Disabling BountyHunters v2.3.9

**Comment by Indyuce** [comment]
Most likely because you don't have an economy plugin. Make sure you have a plugin like Essentials or CMI. You may also double check your server logs as Vault should tell you if it does find one

**Comment by ExceptedPrism3** [comment]
Hello, I do have Vault and essentialsX already installed. I've tested it and it worked with Vault and Essentials only but when I put it along with my other plugins it doesn't work

**Comment by ExceptedPrism3** [comment]
It says this at the start : https://pastebin.com/dhuxvGqG
This after I try to execute the command : https://pastebin.com/RhjiPqam
