### ISSUE TITLE
Hunters not working

### ISSUE THREAD

**Issue by ExceptedPrism3** [Indyuce/bounty-hunters#56]
I get this error code while trying to execute the Hunters command : https://pastebin.com/mPrsFRQv

**Comment by Indyuce** [comment]
Have you tried resetting your language folder and restarting your server?

**Comment by opacityz** [comment]
Having similar issue https://hastebin.com/fuxoditifi.bash

**Comment by ExceptedPrism3** [comment]
Yes I have tried to do so

**Comment by Indyuce** [comment]
The hunter leaderboard was rewritten in 2.3.11, can you give this build a try?

**Comment by ExceptedPrism3** [comment]
Shall I just download it again from the Spigot page again?

**Comment by Indyuce** [comment]
Yup

**Comment by ExceptedPrism3** [comment]
Same issue https://pastebin.com/kjm9x2e5

**Comment by Indyuce** [comment]
@ExceptedPrism3 Can you paste your full latest server logs including the error logs you just pasted?

**Comment by ExceptedPrism3** [comment]
The error after executing /hunters : https://pastebin.com/UD5qpNMH

Latest logs: https://pastebin.com/E84HFvCn

Had to delete some lines to make it able to register in pastebin

**Comment by Indyuce** [comment]
You deleted the most important logs which are startup logs, these are the ones I need to make sure there are no compatibilty/loading issues

**Comment by Indyuce** [comment]
Should be fixed in the latest update

**Comment by ExceptedPrism3** [comment]
Here's the stasrt up logs: https://pastebin.com/7nmeKPVv
