### ISSUE TITLE
An internal error occurred while attempting to perfrom this command.

### ISSUE THREAD

**Issue by Tautrollet** [Indyuce/bounty-hunters#58]
So I am having issues, whenever I try to do commands, I can set bounties on people.
But I can't use /hunters /hunterleaderboard and /bounty.
I have upgraded to 1.16.2 And I tried deleting the file and reinstall it. 
I bought the bountyhunter premium version.

https://pastebin.com/2LSBmFGX
https://gyazo.com/f911936f8e04144ac818e1259e90755a
These are the plugins I have incase something interferes with bountyhunter.
Thank you for helping out.

**Comment by Indyuce** [comment]
Can you pastebin the full server logs (the ones which include the error logs you linked)?
