### ISSUE TITLE
[2.3.11] Leaderboard not displaying any players

### ISSUE THREAD

**Issue by ofseaandstars** [Indyuce/bounty-hunters#59]
**Please include a `latest.log` uploaded to [pastebin.com](https://pastebin.com) here:**
https://pastebin.com/M87BQN7T

**Describe the bug**
The Hunters Leaderboard is blank, even when there are players who have successfully claimed bounties.

**To Reproduce**
1. Have a player claim a bounty successfully.
2. Have the player claim enough to reach level 1.
3. Check /hunters and it'll just say "No Players"

**Expected behavior**
The player who has the most bounties should be displayed on the leaderboard.

**Server info:**
 - Tuinity 1.16.1
 - 2.3.11

**Comment by Indyuce** [comment]
Leaderboard was rehauled in 2.3.13, anything new on that isssue?
