### ISSUE TITLE
Player tracker, formatting...

### ISSUE THREAD

**Issue by Elijeh** [Indyuce/bounty-hunters#6]
- After killing the bountied player, reset the compass back to it's original name (stays at "x blocks").
- The numbers with k won't format (ex. 1000 > 1k).
- Get the InventoryClickEvent NPE in console: https://pastebin.com/0cUPDn3W

**Comment by Indyuce** [comment]
The name of the compass doesn't really matter since plugin checks are based on lore, and it would take some extra performance to change its name back to "Tracking Compass".
Latest commit- NPE fixed and distance is now formatted
