### ISSUE TITLE
Player data not saving

### ISSUE THREAD

**Issue by Hekmopo** [Indyuce/bounty-hunters#62]
Console Error: [BountyHunters] Could not save player data of AlsoHekmo: The last packet successfully received from the server was 43,508,099 milliseconds ago. The last packet sent successfully to the server was 43,508,099 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
>.... [18:00:18 ERROR]: [BountyHunters] Parsed player data: {Level=0, ClaimedBounties=0, SuccessfulBounties=0, IllegalKills=0, IllegalKillStreak=0, RedeemHeads=[]}

I keep getting this error for some reason in the console sometimes not sure what to do here.

**Comment by MoneyDrip** [comment]
I am getting the same error on startup and player-disconnection.
Any solutions? Any support? I also own the premium version of the latest BountyHunters.

Thank you.

**Comment by Indyuce** [comment]
As the error message suggests, you can try adding the `autoReconnect=true` option to avoid losing connection to your database. 

A SQL request looks something like this:\
`mysql://127.0.0.1:3306/databaseName?autoReconnect=true`
Following `mysql://` you have the server IP followed by its port, and then the database name. These are options that you specify in the BH main plugin config. Depending on your needs you might need to add extra command arguments using the `extra-args` option in your plugin config file.

If you'd like to use multiple arguments, use ? for the first one, and separate every argument using &, for example\
`?autoReconnect=true&useSSL=false`

You can try the following MySQL config
```
my-sql:
    enabled: true
    host: serverIp
    port: serverPort
    database: databaseName
    extra-args: '?autoReconnect=true'
    ...
```

The auto reconnect argument makes sure you try and reconnect to your sql database every time you lose connection for a reason or another
