### ISSUE TITLE
Randomly Deleting Bounties

### ISSUE THREAD

**Issue by JohnS19** [Indyuce/bounty-hunters#66]
Bounties are disappearing...

https://paste.gg/p/anonymous/1a0a675f0e2a41aeae761fdd3ab975bc

Server version: 1.16.3
Server software: Tuinity
Plugin version: 2.3.11

**Comment by JohnS19** [comment]
Bounties disappearing...

https://paste.gg/p/anonymous/1a0a675f0e2a41aeae761fdd3ab975bc

**Comment by Indyuce** [comment]
Provided pastebin does not work
