### ISSUE TITLE
Not able to add custom level quotes or titles. Any help? or is it not yet a feature?

### ISSUE THREAD

**Issue by JustJP2K** [Indyuce/bounty-hunters#70]
I was trying to add some custom fun quotes and titles to bounty hunters but it gives me errors. nothing wrong with the yaml file as i put it through a parser and no errors, so im a bit confused. 
Any help? 
Here is my config for the levels

[bounty levels.zip](https://github.com/Indyuce/bounty-hunters/files/5648584/bounty.levels.zip)

**Comment by Indyuce** [comment]
```
# Commands sent when leveling up.
    commands:
```

change it to

```
commands: {}
```
Your parser might not be 100% adapted to Bukkit's yaml configs handling system
