### ISSUE TITLE
Tracking Compass Points in random Direction

### ISSUE THREAD

**Issue by ImperatusMaximus** [Indyuce/bounty-hunters#74]
Good day Indyuce.

I just bought your Premium Version of Bountyhunters.
Everything is looking good so far except the Compass, it points anywhere but to the selected Target. 

Hope this could get fixed somehow :)

Thank you in advance.

**Comment by Indyuce** [comment]
You need to right click the compass which will display an arrow of redstone particles aiming at your target. This system was changed a few updates back (it used to work with the arrow indicated on the actual compass item) because it could be abused to find base spawn points
