### ISSUE TITLE
Crash and lot of money

### ISSUE THREAD

**Issue by kebecode** [Indyuce/bounty-hunters#8]
A player with a bounty was killed, throw an error, the killer got a lot of money and the server crashed.

Using Paper #637 (1.13.2) and economy with EssentialsX

[https://pastebin.com/yxJP4cf1](url)

Is it fixed on 2.2.5?

**Comment by Indyuce** [comment]
Backup and delete your levels.yml, it looks like a configuration issue. This issue is probably "fixed" in the next update - instead of making the server crash, the plugin will display an error message when the levels config file is loaded.

**Comment by Indyuce** [comment]
Closed till more information is provided
