### ISSUE TITLE
Taxes aren't taken for new bounties

### ISSUE THREAD

**Issue by GeneralSarcasam** [Indyuce/bounty-hunters#80]
When players create new bounties, taxes aren't taken off the initial amount. 

It appears that all that needs to be added is `- taxed` near the end of line 180 in this file
https://github.com/Indyuce/bounty-hunters/blob/master/src/net/Indyuce/bountyhunters/command/AddBountyCommand.java#L180

Based on https://github.com/Indyuce/bounty-hunters/blob/master/src/net/Indyuce/bountyhunters/command/AddBountyCommand.java#L150 where it's removed from contributing to a bounty

**Comment by Indyuce** [comment]
Thanks for the easy fix. I'll publish a new plugin build later today
