### ISSUE TITLE
BUG: Bounty Hunters Permission errror when trying to delete bounty

### ISSUE THREAD

**Issue by socksprox** [Indyuce/bounty-hunters#81]
the permission bountyhunters.remove is not working

Im getting the permission errror (not-enough-perms)

**Comment by socksprox** [comment]
I found the bug that hinders players from removing the bounty via command. The wrong permissions for the remove command are being checked. They are in file: BountiesCommand.java line 99: 
`if (!sender.hasPermission("bountyhunters.admin"))` 
there has to be a check for "bountyhunters.remove" instead.

**Comment by Indyuce** [comment]
`/bounties remove <player>` is an admin command. It completely unregisters the bounty and does not give the money back to the creator. The remove permission is for players to be able to remove their contribution to a bounty in the bounty menu.

It's used around line 213 in this file
https://github.com/Indyuce/bounty-hunters/blob/master/src/net/Indyuce/bountyhunters/gui/BountyList.java

Thanks for taking the time to check the code tho!
