### ISSUE TITLE
[QUESTION] Lands compatibility

### ISSUE THREAD

**Issue by srnyx** [Indyuce/bounty-hunters#83]
Is the plugin compatible with [Lands](https://www.spigotmc.org/resources/53313) or no?

**Comment by Indyuce** [comment]
I don't know that plugin, can you briefly describe what it does, what part would cause an incompatibility and how to fix it? Thanks

**Comment by srnyx** [comment]
> can you briefly describe what it does

It's like Towny, but more advanced. It allows people to create a Land, and then they can claim parts of the world (I would say "claim land," but it sounds confusing). People can also create Nations, which are like alliances of Lands. Lands can go to war with each other (as well as Nations).

> what part would cause an incompatibility

People would be able to set bounties on their own land-mates and/or nation-mates.

> how to fix it?

People should only be able to set bounties on others that aren't in their Land or Nation.

**Comment by Indyuce** [comment]
Waiting for the dev to respond

https://github.com/SaberLLC/Saber-Factions/issues/63

**Comment by srnyx** [comment]
> Waiting for the dev to respond
> 
> [SaberLLC/Saber-Factions#63](https://github.com/SaberLLC/Saber-Factions/issues/63)

Saber Factions? Huh?

**Comment by Indyuce** [comment]
Wrong issue ticket
