### ISSUE TITLE
[BUG] when 2 people set a bounty on a player, an incorrect amount of money gets subtracted from the bounty.

### ISSUE THREAD

**Issue by MrPranklez** [Indyuce/bounty-hunters#86]
To replicate this you would need a total of 3 accounts. First, I set the bounty on one of the accounts and top it up with another. Once that has been done I go back to the first account and remove the bounty. You'll see that the amount initially set will get subtracted twice instead of just once. (The player doesn't get double the money back and when the final player removes their contribution they also get all the money back they put into it).

It just appears to be the broadcast that is not showing the correct amount

(when testing this all types of taxes etc were set to 0)

**Comment by Indyuce** [comment]
This will be fixed in the next update
