### ISSUE TITLE
Add saberfaction support

### ISSUE THREAD

**Issue by WoefieProCoder** [Indyuce/bounty-hunters#87]
Hii,

I wanted to know if it was possible to add support for the saberfaction plugin (this is their github https://github.com/SaberLLC/Saber-Factions).

**Comment by Indyuce** [comment]
Waiting for the dev to respond

https://github.com/SaberLLC/Saber-Factions/issues/63

**Comment by Indyuce** [comment]
SaberFactions dev suggested using FactionsBridge
