### ISSUE TITLE
Bounty is not connecting to Vault?

### ISSUE THREAD

**Issue by BakProject** [Indyuce/bounty-hunters#89]
I have installed Vault and BountyHunters Premium. When I load the server Vault loads and enables and but BountyHunters loads and enables, but then it says it cannot load Vault and then disables its self. I just dropped in the .jar and it was doing that. If I am doing something incorrect let me know please.

https://pastebin.com/KLZ7BXyE

**Comment by Indyuce** [comment]
Vault is not an economy plugin, you need an eco plugin like Essentials or CMI
