### ISSUE TITLE
Premium version throwing errors when ran on 1.18

### ISSUE THREAD

**Issue by kaderator2** [Indyuce/bounty-hunters#90]
Paper spigot 1.18, Most recent version of paid Bounty Hunters
Console output when /bounties command ran -

`07.12 05:28:17 [Server] INFO Dead_Of_Pool issued server command: /bounties
07.12 05:28:17 [Server] ERROR null
07.12 05:28:17 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'bounties' in plugin BountyHunters v2.4 - plugin is disabled.
07.12 05:28:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
07.12 05:28:17 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
07.12 05:28:17 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:878) ~[paper-1.18.jar:git-Paper-10]
07.12 05:28:17 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2201) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2012) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1993) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-10]
07.12 05:28:17 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1412) ~[paper-1.18.jar:git-Paper-10]
07.12 05:28:17 [Server] INFO at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-10]
07.12 05:28:17 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1390) ~[paper-1.18.jar:git-Paper-10]
07.12 05:28:17 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1383) ~[paper-1.18.jar:git-Paper-10]
07.12 05:28:17 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
07.12 05:28:17 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1361) ~[paper-1.18.jar:git-Paper-10]
07.12 05:28:17 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1267) ~[paper-1.18.jar:git-Paper-10]
07.12 05:28:17 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.jar:git-Paper-10]
07.12 05:28:17 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
07.12 05:28:27 [Server] INFO ZodicalPeak was slain by DewdropsAtNight`

**Comment by Indyuce** [comment]
1.18 support will be added in the next spigot release
