### ISSUE TITLE
Add KingdomsX support!

### ISSUE THREAD

**Issue by Justusbr0405** [Indyuce/bounty-hunters#93]
Add support for kingdomsx: https://www.spigotmc.org/resources/kingdomsx.77670/
(Free copy can be downloaded thru their discord #dev-builds.)

Kingdomsx.. Has claims as well. This plugin does not respect that.. and with that it's possible to just kill your own k members if you theres a bounty on them.. Say a kingdom puts a bounty on another player inside another kingdom.. then the kingdom of the guy who has that bounty just turns on pvp and kills the guy with a bounty and gives the money to the player with a bounty.. easy money and bounties are useless.

**Comment by Indyuce** [comment]
Will be added
