### ISSUE TITLE
Plugin not loading (errors)

### ISSUE THREAD

**Issue by MidnightSugar** [Indyuce/bounty-hunters#95]
Server log: https://pastebin.com/nATYeFRi
config: https://pastebin.com/vvcbeLNa
levels: https://pastebin.com/CQBse1kt

**Comment by MidnightSugar** [comment]
I found issue is in levels.yml. I had commands [ ] in order to try and disable the commands, I put back the default say commands and its loading now. 

How do I disable the commands section of the config? I don't want to use it.

**Comment by Indyuce** [comment]
`commands: []`
