### ISSUE TITLE
[Feature] "head-hunting" Setting to give the bounty placer the head

### ISSUE THREAD

**Issue by TomLewis** [Indyuce/bounty-hunters#99]
When you toggle on "head-hunting:" when you give the head to the person that placed the bounty, have a setting where the head does not disapear but gets given to the person that placed the bounty.

Bonus points:
In the lore, put down who collected the bounty, the time and date and the price, this will be lost if the head is placed, but its cool if they keep the head in a chest or in a frame.

**Comment by Indyuce** [comment]
Being implemented, this will be possible by toggling on the option `drop-head.creator`

**Comment by TomLewis** [comment]
Woohoo!
